name: Build and Dockerize

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: docker build -t prototype-app:latest .

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: prototype-app-image
        path: |
          target/demo-0.0.1-SNAPSHOT.war
